# Generated by Django 3.2.7 on 2022-06-07 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0002_personaldetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmokingHabits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_smoking_habits', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive'), ('Non-Smoker', 'Non-Smoker')], max_length=20)),
                ('years_smoked', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('average_pack', models.PositiveIntegerField()),
                ('passive_intensity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
