# Generated by Django 3.2.7 on 2022-06-07 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_smokinghabits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokinghabits',
            name='average_pack',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='smokinghabits',
            name='years_smoked',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
