# Generated by Django 3.2.7 on 2022-06-07 15:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0005_alcoholhabits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(choices=[('Parent', 'Parent'), ('Other Relative', 'Other Relative'), ('No Risk', 'No Risk')], max_length=20)),
                ('number_of_relatives', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
