# Generated by Django 3.2.7 on 2022-06-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0006_geneticrisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChronicConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_lung_diseases', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('frequent_chest_pain', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('chronic_cold', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
