# Generated by Django 3.2.7 on 2022-06-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firstapp', '0008_obesity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherSymptons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coughing_blood', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fatty_diet', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('tobacco', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('balance_problems', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('heart_problems', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_loss', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('physical_activity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fatigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
