# Generated by Django 3.2.7 on 2022-06-08 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_fatigue_lifestyle_othersymptons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokinghabits',
            name='average_pack',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='smokinghabits',
            name='years_smoked',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
