# Generated by Django 3.2.7 on 2022-06-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20220608_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smokinghabits',
            name='average_pack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smokinghabits',
            name='passive_intensity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True),
        ),
    ]
